// Mount-specific catalogs.
window.DEADLANDS_MOUNT_HINDRANCE_IDS = [
  "h000",
  "h001",
  "h003",
  "h004",
  "h007",
  "h008",
  "h016",
  "h018",
  "h019",
  "h020",
  "h025",
  "h031",
  "h032",
  "h033",
  "h037",
  "h039",
  "h040",
  "h046",
  "h048",
  "h049",
  "h050",
  "h051",
  "h052",
  "h053",
  "h055",
  "h057",
  "h058",
  "h064",
  "h065",
  "h066",
  "h067",
  "h068",
  "h070",
  "h071",
  "h074",
  "h077",
  "h079",
  "h081",
  "h082",
  "h085",
  "h086",
  "h088",
  "h089",
  "h090",
  "h091",
  "h092",
  "h093",
  "h094",
  "h095",
  "h097",
  "h098",
  "h099",
  "h100",
  "h103",
];

window.DEADLANDS_CATALOG_MOUNT_GEAR = [
  {
    id: "mg001",
    key: "saddle",
    kind: "gear",
    name: "Седло",
    weight: 30,
    price: "$25",
    priceCents: 2500,
    note: "Базовое седло для верховой езды",
  },
  {
    id: "mg002",
    key: "saddlebags",
    kind: "gear",
    name: "Седельные сумки",
    weight: 5,
    price: "$5",
    priceCents: 500,
    note: "Сумки для груза и походных мелочей",
  },
  {
    id: "mg003",
    key: "rifleScabbard",
    kind: "gear",
    name: "Чехол для винтовки",
    weight: 0.5,
    price: "$3",
    priceCents: 300,
    note: "Позволяет возить винтовку на лошади, выхватывание на скаку считается действием",
  },
  {
    id: "mg004",
    key: "bridle",
    kind: "gear",
    name: "Удила и упряжь",
    weight: 1,
    price: "$2",
    priceCents: 200,
    note: "Базовый комплект контроля лошади. Без него проверки Верховой езды бросаются со штрафом -2",
  },
  {
    id: "mg005",
    key: "stirrups",
    kind: "gear",
    name: "Путлища",
    weight: 1,
    price: "$1",
    priceCents: 100,
    note: "Ремни для ног. Если конь стреножен ими, он не может убежать при проверках на испуг от ночных чудовищ, оставаясь на месте",
  },
  {
    id: "mg006",
    key: "arcaneWard",
    kind: "gear",
    name: "Арканный оберег",
    weight: 0.3,
    price: "$50",
    priceCents: 5000,
    note: "Мешочек с защитными травами и духами, привязанный к гриве. Этот оберег дает лошади +2 к проверкам храбрости против чудовищ",
  },
  {
    id: "mg007",
    key: "ghostCoalLamp",
    kind: "gear",
    name: "Фара на призрачном угле",
    weight: 3,
    price: "$25",
    priceCents: 2500,
    note: "Крепится на оголовье лошади. Освещает конус перед конем на 24 метра вперед, полностью игнорируя штрафы за темноту, но выдает позицию всадника",
  },
];

window.DEADLANDS_MOUNT_GEAR_BY_KEY = Object.fromEntries(
  window.DEADLANDS_CATALOG_MOUNT_GEAR.map(item => [item.key, item])
);
