window.DEADLANDS_CATALOG_WEAPONS = [
    {
      "id": "w000",
      "name": "Баллард '72 (.56)",
      "group": "Винтовки",
      "range": "12/24/48",
      "damage": "2d10",
      "ap": 2,
      "price": "$24",
      "weight": 11,
      "magazine": 1,
      "mode": "1В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w001",
      "name": "Баллард Экспресс (.44-40/.50)",
      "group": "Винтовки",
      "range": "11/22/44",
      "damage": "2d10",
      "ap": 2,
      "price": "$30",
      "weight": 11,
      "magazine": 1,
      "mode": "1В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w002",
      "name": "Винчестер '73 (.44-40)",
      "group": "Винтовки",
      "range": "11/22/44",
      "damage": "2d8",
      "ap": 2,
      "price": "$25",
      "weight": 7,
      "magazine": 15,
      "mode": "1В",
      "mc": "d8",
      "notes": ""
    },
    {
      "id": "w003",
      "name": "Винчестер '76 (.45)",
      "group": "Винтовки",
      "range": "12/24/48",
      "damage": "2d8",
      "ap": 2,
      "price": "$40",
      "weight": 7,
      "magazine": 15,
      "mode": "1В",
      "mc": "d8",
      "notes": ""
    },
    {
      "id": "w004",
      "name": "Кольт-Патерсон",
      "group": "Винтовки",
      "range": "12/24/48",
      "damage": "2d10",
      "ap": 2,
      "price": "—",
      "weight": 7,
      "magazine": "—",
      "mode": "1В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w005",
      "name": "Модель '36 (.69)",
      "group": "Винтовки",
      "range": "12/24/48",
      "damage": "2d10",
      "ap": 2,
      "price": "$25",
      "weight": 12,
      "magazine": 1,
      "mode": "1В",
      "mc": "d8",
      "notes": "ПЗ 2"
    },
    {
      "id": "w006",
      "name": "Миссисипи 1841 (.54)",
      "group": "Винтовки",
      "range": "12/24/48",
      "damage": "2d10",
      "ap": 2,
      "price": "$16",
      "weight": 8,
      "magazine": 1,
      "mode": "1В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w007",
      "name": "Револьверная винтовка Кольта (.56)",
      "group": "Винтовки",
      "range": "12/24/48",
      "damage": "2d10",
      "ap": 2,
      "price": "$24",
      "weight": 11,
      "magazine": 5,
      "mode": "1В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w008",
      "name": "Ремингтон '73 (.44-90)",
      "group": "Винтовки",
      "range": "12/24/48",
      "damage": "2d8+1",
      "ap": 2,
      "price": "$20",
      "weight": 7,
      "magazine": 1,
      "mode": "1В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w009",
      "name": "Спортивная винтовка Эванса (.44)",
      "group": "Винтовки",
      "range": "12/24/48",
      "damage": "2d8",
      "ap": 2,
      "price": "$30",
      "weight": 12,
      "magazine": 34,
      "mode": "1В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w010",
      "name": "Спрингфилд '66 (.58)",
      "group": "Винтовки",
      "range": "12/24/30",
      "damage": "2d10",
      "ap": 2,
      "price": "$8",
      "weight": 9,
      "magazine": 1,
      "mode": "1В",
      "mc": "—",
      "notes": "ПЗ 2"
    },
    {
      "id": "w011",
      "name": "Шарпс Биг 50 (.50)",
      "group": "Винтовки",
      "range": "15/30/60",
      "damage": "2d10",
      "ap": 2,
      "price": "$20",
      "weight": 10,
      "magazine": 1,
      "mode": "1В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w012",
      "name": "Энфилд (.58)",
      "group": "Винтовки",
      "range": "8/15/30",
      "damage": "2d10",
      "ap": 2,
      "price": "$12",
      "weight": 9,
      "magazine": 1,
      "mode": "1В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w013",
      "name": "Карабин Ле Ма (.42) & дробовик (16)",
      "group": "Карабины",
      "range": "10/20/40",
      "damage": "2d8",
      "ap": 2,
      "price": "$35",
      "weight": 9,
      "magazine": "—",
      "mode": "1В",
      "mc": "—",
      "notes": "ПЗ 1, дробовик"
    },
    {
      "id": "w014",
      "name": "Спенсер (.56)",
      "group": "Карабины",
      "range": "6/12/24",
      "damage": "1-3d6",
      "ap": "—",
      "price": "—",
      "weight": 9,
      "magazine": 7,
      "mode": "1В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w015",
      "name": "Снайпер '55 (.57)",
      "group": "Карабины",
      "range": "10/20/40",
      "damage": "2d8",
      "ap": 2,
      "price": "$25",
      "weight": 8,
      "magazine": 1,
      "mode": "1В",
      "mc": "—",
      "notes": "ПЗ 2"
    },
    {
      "id": "w016",
      "name": "Шарп '55 (.57)",
      "group": "Карабины",
      "range": "10/20/40",
      "damage": "2d8+1",
      "ap": 2,
      "price": "$8",
      "weight": 8,
      "magazine": 1,
      "mode": "1В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w017",
      "name": "Двустволка (12 кал.)",
      "group": "Ружья",
      "range": "6/12/24",
      "damage": "1-3d6",
      "ap": "—",
      "price": "$35",
      "weight": 8,
      "magazine": 2,
      "mode": "1В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w018",
      "name": "Двустволка обрез (12 кал.)",
      "group": "Ружья",
      "range": "3/6/12",
      "damage": "1-3d6",
      "ap": "—",
      "price": "$35",
      "weight": 5,
      "magazine": 2,
      "mode": "1В",
      "mc": "—",
      "notes": "дробовик"
    },
    {
      "id": "w019",
      "name": "Многозарядное ружьё (12 кал.)",
      "group": "Ружья",
      "range": "6/12/24",
      "damage": "1-3d6",
      "ap": "—",
      "price": "$35",
      "weight": 8,
      "magazine": 2,
      "mode": "1В",
      "mc": "—",
      "notes": "дробовик"
    },
    {
      "id": "w020",
      "name": "Одноствольное ружьё (12 кал.)",
      "group": "Ружья",
      "range": "6/12/24",
      "damage": "1-3d6",
      "ap": "—",
      "price": "$25",
      "weight": 6,
      "magazine": 1,
      "mode": "1В",
      "mc": "—",
      "notes": "дробовик"
    },
    {
      "id": "w021",
      "name": "Револьверное ружьё Кольта (12 кал.)",
      "group": "Ружья",
      "range": "6/12/24",
      "damage": "1-3d6",
      "ap": "—",
      "price": "$45",
      "weight": 10,
      "magazine": 5,
      "mode": "1В",
      "mc": "d6",
      "notes": "дробовик"
    },
    {
      "id": "w022",
      "name": "Английский Дерринджер 1840 (.36)",
      "group": "Дерринджеры и пеппербоксы",
      "range": "2/4/8",
      "damage": "2d4+1",
      "ap": 1,
      "price": "$5",
      "weight": 1,
      "magazine": 1,
      "mode": "1В",
      "mc": "—",
      "notes": "потайное"
    },
    {
      "id": "w023",
      "name": "Бульдог (.44)",
      "group": "Дерринджеры и пеппербоксы",
      "range": "2/3/6",
      "damage": "2d6",
      "ap": 1,
      "price": "$12",
      "weight": 1.5,
      "magazine": 2,
      "mode": "1В; 2В",
      "mc": "—",
      "notes": "потайное"
    },
    {
      "id": "w024",
      "name": "Двойной Дерринджер Ремингтона (.41)",
      "group": "Дерринджеры и пеппербоксы",
      "range": "3/5/10",
      "damage": "2d6",
      "ap": 1,
      "price": "$8",
      "weight": 0.5,
      "magazine": 2,
      "mode": "1В",
      "mc": "—",
      "notes": "потайное"
    },
    {
      "id": "w025",
      "name": "Карманный Кольт 1849 (.31)",
      "group": "Дерринджеры и пеппербоксы",
      "range": "2/4/8",
      "damage": "2d4+1",
      "ap": 1,
      "price": "$5",
      "weight": 0.5,
      "magazine": 5,
      "mode": "1В",
      "mc": "—",
      "notes": "потайное"
    },
    {
      "id": "w026",
      "name": "Кольт Дерринджер (.41)",
      "group": "Дерринджеры и пеппербоксы",
      "range": "2/4/8",
      "damage": "2d6",
      "ap": 1,
      "price": "$4",
      "weight": 0.5,
      "magazine": 1,
      "mode": "1В",
      "mc": "—",
      "notes": "потайное"
    },
    {
      "id": "w027",
      "name": "Пеппербокс Рунерруса (.22)",
      "group": "Дерринджеры и пеппербоксы",
      "range": "2/4/8",
      "damage": "2d4+1",
      "ap": 1,
      "price": "—",
      "weight": 0.5,
      "magazine": 8,
      "mode": "1В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w028",
      "name": "Пистолет-кинжал Вессона (.41)",
      "group": "Дерринджеры и пеппербоксы",
      "range": "3/5/10",
      "damage": "2d6",
      "ap": 1,
      "price": "$6",
      "weight": 1,
      "magazine": 1,
      "mode": "1В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w029",
      "name": "Армейский Кольт '60 (.44)",
      "group": "Револьверы ОД",
      "range": "6/12/24",
      "damage": "2d6+1",
      "ap": 1,
      "price": "$15",
      "weight": 3,
      "magazine": 6,
      "mode": "1В; 6В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w030",
      "name": "Гризвальд и Ганнисон (.36)",
      "group": "Револьверы ОД",
      "range": "5/10/20",
      "damage": "2d6",
      "ap": 1,
      "price": "$8",
      "weight": 3,
      "magazine": 6,
      "mode": "1В; 6В",
      "mc": "—",
      "notes": "ПЗ 2"
    },
    {
      "id": "w031",
      "name": "Кольт «Драгун»",
      "group": "Револьверы ОД",
      "range": "5/10/20",
      "damage": "2d6+1",
      "ap": 1,
      "price": "$11",
      "weight": 4,
      "magazine": 6,
      "mode": "1В; 6В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w032",
      "name": "Кольт «Миротворец» (.45)",
      "group": "Револьверы ОД",
      "range": "6/12/24",
      "damage": "2d6+1",
      "ap": 1,
      "price": "$17",
      "weight": 2,
      "magazine": 6,
      "mode": "1В; 6В",
      "mc": "d6",
      "notes": ""
    },
    {
      "id": "w033",
      "name": "Кольт «Уолкер» (.44)",
      "group": "Револьверы ОД",
      "range": "6/12/24",
      "damage": "2d8",
      "ap": 1,
      "price": "$12",
      "weight": 5,
      "magazine": 6,
      "mode": "1В; 6В",
      "mc": "d8",
      "notes": ""
    },
    {
      "id": "w034",
      "name": "Кольт Бантлайна (.45)",
      "group": "Револьверы ОД",
      "range": "8/15/30",
      "damage": "2d6+1",
      "ap": 1,
      "price": "$500",
      "weight": 3,
      "magazine": 6,
      "mode": "1В; 6В",
      "mc": "d6",
      "notes": ""
    },
    {
      "id": "w035",
      "name": "Ле Ма (.40) & дробовик (16)",
      "group": "Револьверы ОД",
      "range": "6/12/24",
      "damage": "2d6 / 1-3d6",
      "ap": 1,
      "price": "$25",
      "weight": 4,
      "magazine": "9+1",
      "mode": "1В; 6В",
      "mc": "d6",
      "notes": "дробовик"
    },
    {
      "id": "w036",
      "name": "Семизарядник Муара (.32)",
      "group": "Револьверы ОД",
      "range": "6/12/24",
      "damage": "2d6+1",
      "ap": 1,
      "price": "—",
      "weight": 3,
      "magazine": 7,
      "mode": "1В; 6В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w037",
      "name": "Смит-Вессон №3 (.44)",
      "group": "Револьверы ОД",
      "range": "5/10/20",
      "damage": "2d6",
      "ap": 1,
      "price": "$13",
      "weight": 2,
      "magazine": 6,
      "mode": "1В; 6В",
      "mc": "d6",
      "notes": "экстрактор"
    },
    {
      "id": "w038",
      "name": "Флотский Кольт (.36)",
      "group": "Револьверы ОД",
      "range": "5/10/20",
      "damage": "2d6+1",
      "ap": 1,
      "price": "$10",
      "weight": 2.5,
      "magazine": 6,
      "mode": "1В; 6В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w039",
      "name": "Армейский Кольт '77 (.44)",
      "group": "Револьверы ДД",
      "range": "6/12/24",
      "damage": "2d6+1",
      "ap": 1,
      "price": "$18",
      "weight": 2.5,
      "magazine": 6,
      "mode": "1В; 6В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w040",
      "name": "Бомон-Адамс (.36)",
      "group": "Револьверы ДД",
      "range": "5/10/20",
      "damage": "2d6",
      "ap": 1,
      "price": "$10",
      "weight": 2.5,
      "magazine": 6,
      "mode": "1В; 6В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w041",
      "name": "Вебей КИ.П. (.45)",
      "group": "Револьверы ДД",
      "range": "5/10/20",
      "damage": "2d6+1",
      "ap": 1,
      "price": "$18",
      "weight": 2,
      "magazine": 6,
      "mode": "1В; 6В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w042",
      "name": "Кольт «Громовержец» (.41)",
      "group": "Револьверы ДД",
      "range": "6/12/24",
      "damage": "2d6",
      "ap": 1,
      "price": "$14",
      "weight": 2,
      "magazine": 6,
      "mode": "1В; 6В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w043",
      "name": "Кольт «Молния» (.38)",
      "group": "Револьверы ДД",
      "range": "6/12/24",
      "damage": "2d6+1",
      "ap": 1,
      "price": "$13",
      "weight": 2,
      "magazine": 6,
      "mode": "1В; 6В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w044",
      "name": "Кольт «Фронтир» (.32-20)",
      "group": "Револьверы ДД",
      "range": "5/10/20",
      "damage": "2d6",
      "ap": 1,
      "price": "$8",
      "weight": 2,
      "magazine": 6,
      "mode": "1В; 6В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w045",
      "name": "Револьвер Старра (.44)",
      "group": "Револьверы ДД",
      "range": "5/10/20",
      "damage": "2d4+1",
      "ap": 1,
      "price": "$8",
      "weight": 1.5,
      "magazine": 6,
      "mode": "1В; 6В",
      "mc": "—",
      "notes": "ПЗ 2"
    },
    {
      "id": "w046",
      "name": "Гатлинг-винтовка (.45)",
      "group": "Оружие Гатлинга",
      "range": "12/24/48",
      "damage": "2d8",
      "ap": 2,
      "price": "$1200",
      "weight": 13,
      "magazine": 12,
      "mode": "авто 2",
      "mc": "d6",
      "notes": ""
    },
    {
      "id": "w047",
      "name": "Гатлинг-дробовик",
      "group": "Оружие Гатлинга",
      "range": "6/12/24",
      "damage": "1-3d6",
      "ap": 2,
      "price": "$1500",
      "weight": 15,
      "magazine": 12,
      "mode": "авто 2",
      "mc": "d8",
      "notes": "дробовик"
    },
    {
      "id": "w048",
      "name": "Гатлинг-револьвер (.45)",
      "group": "Оружие Гатлинга",
      "range": "6/12/24",
      "damage": "2d6+1",
      "ap": 1,
      "price": "$800",
      "weight": 5,
      "magazine": 12,
      "mode": "авто 2",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w049",
      "name": "Пулемёт Гатлинга (.45)",
      "group": "Оружие Гатлинга",
      "range": "12/24/48",
      "damage": "2d8",
      "ap": 2,
      "price": "$1500",
      "weight": 40,
      "magazine": 100,
      "mode": "авто 3",
      "mc": "—",
      "notes": "стационарное"
    },
    {
      "id": "w050",
      "name": "Бола",
      "group": "Прочее",
      "range": "2/4/8",
      "damage": "сила+1",
      "ap": "—",
      "price": "$3",
      "weight": 0.5,
      "magazine": 1,
      "mode": "1В",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w051",
      "name": "Лук",
      "group": "Прочее",
      "range": "6/12/24",
      "damage": "2d6",
      "ap": "—",
      "price": "$3",
      "weight": 2,
      "magazine": 1,
      "mode": "1В",
      "mc": "—",
      "notes": "см. описание"
    },
    {
      "id": "w052",
      "name": "1 динамитная шашка",
      "group": "Взрывчатка",
      "range": "2/4/8",
      "damage": "2d6",
      "ap": "—",
      "price": "$3",
      "weight": 0.5,
      "magazine": 1,
      "mode": "—",
      "mc": "—",
      "notes": "МШ"
    },
    {
      "id": "w053",
      "name": "2 динамитные шашки",
      "group": "Взрывчатка",
      "range": "2/4/8",
      "damage": "3d6",
      "ap": "—",
      "price": "$6",
      "weight": 1,
      "magazine": 1,
      "mode": "—",
      "mc": "—",
      "notes": "МШ"
    },
    {
      "id": "w054",
      "name": "4 динамитные шашки",
      "group": "Взрывчатка",
      "range": "2/4/8",
      "damage": "4d6",
      "ap": "—",
      "price": "$12",
      "weight": 2,
      "magazine": 1,
      "mode": "—",
      "mc": "—",
      "notes": "СШ"
    },
    {
      "id": "w055",
      "name": "8 динамитных шашек",
      "group": "Взрывчатка",
      "range": "1/2/4",
      "damage": "5d6",
      "ap": "—",
      "price": "$24",
      "weight": 4,
      "magazine": 1,
      "mode": "—",
      "mc": "—",
      "notes": "БШ; рекр."
    },
    {
      "id": "w056",
      "name": "Нитроглицерин (8 унций)",
      "group": "Взрывчатка",
      "range": "2/4/8",
      "damage": "3d6",
      "ap": "—",
      "price": "$1.25",
      "weight": 0.5,
      "magazine": 1,
      "mode": "—",
      "mc": "—",
      "notes": "БШ"
    },
    {
      "id": "w057",
      "name": "Боевая дубинка",
      "group": "Холодное оружие",
      "range": "—",
      "damage": "сила+d6",
      "ap": "—",
      "price": "$3",
      "weight": 3,
      "magazine": "—",
      "mode": "—",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w058",
      "name": "Дубинка",
      "group": "Холодное оружие",
      "range": "—",
      "damage": "сила+d4",
      "ap": "—",
      "price": "$1",
      "weight": 1,
      "magazine": "—",
      "mode": "—",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w059",
      "name": "Кнут",
      "group": "Холодное оружие",
      "range": "—",
      "damage": "сила+d4",
      "ap": "—",
      "price": "$10",
      "weight": 2,
      "magazine": "—",
      "mode": "—",
      "mc": "—",
      "notes": "При подъёме на атаке вместо дополнительного урона защита цели уменьшается на 1, дальность +2"
    },
    {
      "id": "w060",
      "name": "Копьё",
      "group": "Холодное оружие",
      "range": "—",
      "damage": "сила+d6",
      "ap": "—",
      "price": "$3",
      "weight": 5,
      "magazine": "—",
      "mode": "—",
      "mc": "—",
      "notes": "Защита +1, дальность +1, Двуручное"
    },
    {
      "id": "w061",
      "name": "Лассо",
      "group": "Холодное оружие",
      "range": "—",
      "damage": "—",
      "ap": "—",
      "price": "$4",
      "weight": 3,
      "magazine": "—",
      "mode": "—",
      "mc": "—",
      "notes": "Уловка против Ловкости (навык Драки). Успех: защита −2 до начала следующего хода врага. Подъём: враг спутан и в шоке. Дальность +2"
    },
    {
      "id": "w062",
      "name": "Нож",
      "group": "Холодное оружие",
      "range": "—",
      "damage": "сила+d4",
      "ap": "—",
      "price": "$2",
      "weight": 1,
      "magazine": "—",
      "mode": "—",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w063",
      "name": "Нож «Боуи»",
      "group": "Холодное оружие",
      "range": "—",
      "damage": "сила+d4+1",
      "ap": 1,
      "price": "$4",
      "weight": 2,
      "magazine": "—",
      "mode": "—",
      "mc": "—",
      "notes": ""
    },
    {
      "id": "w064",
      "name": "Стрелы",
      "group": "Боеприпасы",
      "range": "—",
      "damage": "—",
      "ap": "—",
      "price": "$2",
      "weight": 4,
      "magazine": "—",
      "mode": "—",
      "mc": "—",
      "notes": "Кол-во: 20"
    },
    {
      "id": "w065",
      "name": "Рев. патроны (.22–.38)",
      "group": "Боеприпасы",
      "range": "—",
      "damage": "—",
      "ap": "—",
      "price": "$2",
      "weight": 3,
      "magazine": "—",
      "mode": "—",
      "mc": "—",
      "notes": "Кол-во: 50"
    },
    {
      "id": "w066",
      "name": "Рев. патроны (.40–.50)",
      "group": "Боеприпасы",
      "range": "—",
      "damage": "—",
      "ap": "—",
      "price": "$3",
      "weight": 5,
      "magazine": "—",
      "mode": "—",
      "mc": "—",
      "notes": "Кол-во: 50"
    },
    {
      "id": "w067",
      "name": "Вин. патроны (.38–.52)",
      "group": "Боеприпасы",
      "range": "—",
      "damage": "—",
      "ap": "—",
      "price": "$4",
      "weight": 6,
      "magazine": "—",
      "mode": "—",
      "mc": "—",
      "notes": "Кол-во: 50"
    },
    {
      "id": "w068",
      "name": "Вин. патроны (.56+)",
      "group": "Боеприпасы",
      "range": "—",
      "damage": "—",
      "ap": "—",
      "price": "$5",
      "weight": 8,
      "magazine": "—",
      "mode": "—",
      "mc": "—",
      "notes": "Кол-во: 50"
    },
    {
      "id": "w069",
      "name": "Порох, пуля и пыж",
      "group": "Боеприпасы",
      "range": "—",
      "damage": "—",
      "ap": "—",
      "price": "$1",
      "weight": 4,
      "magazine": "—",
      "mode": "—",
      "mc": "—",
      "notes": "Кол-во: 20"
    },
    {
      "id": "w070",
      "name": "Капсюли-детонаторы",
      "group": "Боеприпасы",
      "range": "—",
      "damage": "—",
      "ap": "—",
      "price": "50¢",
      "weight": 1,
      "magazine": "—",
      "mode": "—",
      "mc": "—",
      "notes": "Кол-во: 60"
    },
    {
      "id": "w071",
      "name": "Патроны для ружья",
      "group": "Боеприпасы",
      "range": "—",
      "damage": "—",
      "ap": "—",
      "price": "$2",
      "weight": 2,
      "magazine": "—",
      "mode": "—",
      "mc": "—",
      "notes": "Кол-во: 20"
    }
];
